# Generated by Django 5.2.6 on 2025-10-30 17:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0010_loantransaction'),
        ('loginApp', '0003_alter_customersignup_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanrequest',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='loanrequest',
            name='request_date',
        ),
        migrations.RemoveField(
            model_name='loanrequest',
            name='status_date',
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='bank_statement',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='identity_proof',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='income_proof',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='loan_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='occupation_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='property_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='property_documents',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='property_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='customerloan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='loancategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loanApp.loancategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginApp.customersignup'),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
