# Generated by Django 5.2.6 on 2025-11-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0011_remove_loanrequest_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loancategory',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Enter interest rate (e.g. 8.50 for 8.5%)', max_digits=5),
            preserve_default=False,
        ),
    ]
