# Generated by Django 5.2.6 on 2025-11-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0012_loancategory_interest_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='request_date',
            field=models.DateField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
