# Generated by Django 5.2.6 on 2025-11-10 19:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0014_loanrequest_status_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='request_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
