# Generated by Django 5.2.6 on 2025-11-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_name', models.CharField(max_length=100)),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Enter interest rate (e.g. 8.50 for 8.5%)', max_digits=5)),
            ],
        ),
    ]
