# Generated by Django 5.2.6 on 2025-11-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0013_loanrequest_request_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='status_date',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
